import "./globals.css";
import NavBar from "@/Components/NavBar";
import Footer from "@/Components/Footer";
import Drawer from "@/Components/Drawer";

import { fontFamily } from "@/Components/fontStyle";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={fontFamily.className}>
        <NavBar/>
        {/* <Drawer/> */}
        {children}
        <Footer/>        
        
        </body>
    </html>
  );
}
