import "./globals.css";

import { fontFamily } from "@/Components/fontStyle";
import { config } from "@fortawesome/fontawesome-svg-core";
import "@fortawesome/fontawesome-svg-core/styles.css";
import Main from "./main";
config.autoAddCss = false;

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {

  return (
    <html lang="en">
      <body className={fontFamily.className}>
        <Main>
        {children}

        </Main>
      </body>
    </html>
  );
}
